apps/recruitment/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

urlpatterns = patterns('',
    # Recruitment
    url(r'^$', 'recruitment.views.register', name=u'register'),
    url(r'^confirm_email_address/(?P<pk>\d+)/(?P<email_hash>\w+)/$', 'recruitment.views.confirm_email_address', name=u'confirm_email_address'),
    url(r'^confirm_application/(?P<pk>\d+)/(?P<confirmation_hash>\w+)/$', 'recruitment.views.confirm_application', name=u'confirm_application'),
    url(r'^mypage/$', 'recruitment.views.mypage', name=u'mypage'),
    url(r'^edit_my_profile/$', 'recruitment.views.edit_my_profile', name=u'edit_my_profile'),
    url(r'^apply_for_position/$', 'recruitment.views.apply_for_position', name=u'apply_for_position'),

    # Backoffice
    url(r'^backoffice/$', TemplateView.as_view(template_name=u'recruitment/backoffice.html'), name='backoffice'),
    url(r'^backoffice/list_applications/$', 'recruitment.views.list_applications', name='list_applications'),
    url(r'^backoffice/show_application/(?P<pk>\d+)/$', 'recruitment.views.show_application', name='show_application'),

    # Comments
    url(r'^comment/add/(?P<pk>\d+)/$', 'recruitment.views.add_application_comment', name='add_application_comment'),

    url(r'^set_language/(?P<code>[\w\-]+)$', 'recruitment.views.set_language', name='set_language')
)

project/urls.py
from django.conf.urls import patterns, include, url
from django.core.urlresolvers import reverse_lazy

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'project.views.home', name='home'),
    url(r'^recruitment/', include('recruitment.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # Django Auth
    url(r'^login/$',  'django.contrib.auth.views.login',  {'template_name': 'auth/login.html'},  name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'template_name': 'auth/logout.html'}, name='logout'),
    url(r'^password_change/$', 'django.contrib.auth.views.password_change', {'template_name': 'auth/password_change_form.html', 'post_change_redirect' : reverse_lazy('mypage')}, name='password_change'),

)

apps/recruitment/models.py
# -*- coding: utf-8 -*-

from django_fsm.db.fields import FSMField, transition
from django.contrib.auth.models import User
from django.contrib.sites.models import Site
from django.core.mail import send_mail
from django.db import models
from django.db.models import Q
from django.template import Context, loader
from django.utils.translation import get_language, ugettext_lazy, ugettext as _
import hashlib

class Language(models.Model):
    u"""http://www.i18nguy.com/unicode/language-identifiers.html"""
    code = models.CharField(ugettext_lazy(u'Language code'), max_length=50)
    name = models.CharField(ugettext_lazy(u'Language name'), max_length=50)

    class Meta:
        verbose_name = ugettext_lazy(u'language')
        verbose_name_plural = ugettext_lazy(u'languages')

    def __unicode__(self):
        return u'%s %s' % (self.code, self.name)

class StringTranslation(models.Model):
    u"""A translation for a string."""
    string   = models.CharField(ugettext_lazy(u'String'), max_length=25)
    language = models.ForeignKey(Language)
    default  = models.BooleanField(ugettext_lazy(u'Default language'), default=False)

    class Meta:
        verbose_name = ugettext_lazy(u'string translation')
        verbose_name_plural = ugettext_lazy(u'string translations')

    def __unicode__(self):
        return self.string

class TextTranslation(models.Model):
    u"""A translation for a text."""
    text     = models.TextField(ugettext_lazy(u'Text'))
    language = models.ForeignKey(Language)
    default  = models.BooleanField(ugettext_lazy(u'Default language'), default=False)

    class Meta:
        verbose_name = ugettext_lazy(u'text translation')
        verbose_name_plural = ugettext_lazy(u'text translations')

    def __unicode__(self):
        return self.text

class BaseInfo(models.Model):
    translations = models.ManyToManyField(StringTranslation)

    class Meta:
        abstract = True
        ordering = ('translations__string',)

    def __unicode__(self):
        u"""Either get the language we want, or get the default language. 
        Will probably throw terrible exceptions if neither is found. 
        That's a feature. The translations are regarded as broken if 
        neither a translation nor a default exists."""
        lang = get_language().lower()
        ts   = self.translations.filter(Q(language__code__icontains=lang) | Q(default=True)).select_related(depth=2)
        if len(ts) > 1:
            for t in ts:
                if lang in t.language.code.lower():
                    return t.string
        else:
            if ts[0].default:
                return ts[0].string

        assert False, u'Got neither a translation nor a default language for %s, id: %s' % (self, self.pk)

class StudyArea(BaseInfo):
    class Meta:
        verbose_name = ugettext_lazy(u'area of study')
        verbose_name_plural = ugettext_lazy(u'areas of study')

class DriverLicense(BaseInfo):
    class Meta:
        verbose_name = ugettext_lazy(u'driver license')
        verbose_name_plural = ugettext_lazy(u'driver licenses')

class ForkLiftLicense(BaseInfo):
    class Meta:
        verbose_name = ugettext_lazy(u'forklift license')
        verbose_name_plural = ugettext_lazy(u'forklift licenses')

class ShirtSize(BaseInfo):
    class Meta:
        verbose_name = ugettext_lazy(u'shirt size')
        verbose_name_plural = ugettext_lazy(u'shirt sizes')

class Person(models.Model):
    u"""Contains information about a person."""
    fname = models.CharField(ugettext_lazy(u'First name'), max_length=50)
    lname = models.CharField(ugettext_lazy(u'Last name'), max_length=50)
    ssn = models.CharField(ugettext_lazy(u'Social security number'), help_text=ugettext_lazy(u'Enter your social security number, using ten or twelve digits.'), max_length=50)
    phone = models.CharField(ugettext_lazy(u'Phone number'), max_length=15) # Phone numbers are max 15 digits long.
    email = models.EmailField(ugettext_lazy(u'E-mail'), max_length=50)

    study_area = models.ForeignKey(StudyArea, verbose_name=ugettext_lazy(u'area of study')) # , verbose_name=ugettext_lazy(), verbose_name_plural=ugettext_lazy()
    starting_year = models.IntegerField(ugettext_lazy(u'Starting year'))
    driver_license = models.ManyToManyField(DriverLicense, verbose_name=ugettext_lazy(u'driver license'), null=True, blank=True) 
    forklift_license = models.ManyToManyField(ForkLiftLicense, verbose_name=ugettext_lazy(u'forklift license'), help_text=ugettext_lazy(u'<a href="http://www.youtube.com/watch?v=9z77oztO6UQ">Safety first!</a>'), null=True, blank=True) 
    allergies = models.TextField(ugettext_lazy(u'Allergies and food preferences'), blank=True)
    shirt_size = models.ForeignKey(ShirtSize, verbose_name=ugettext_lazy(u'shirt size'))

    # TODO: Gör om till OneToOneField
    user = models.ForeignKey(User, blank=True, null=True)

    created = models.DateTimeField(ugettext_lazy(u'Created'), auto_now_add=True) 
    email_confirmed = models.BooleanField(ugettext_lazy(u'E-mail address confirmed'), default=False)

    class Meta:
        verbose_name = ugettext_lazy(u'person')
        verbose_name_plural = ugettext_lazy(u'people')
        ordering = ('fname', 'lname')

        permissions = (
                    (u'can_administrate', _(u'Can administrate')),
                )

    def __unicode__(self):
        return u'%s %s' % (self.fname, self.lname)

    @property
    def email_hash(self):
        return hashlib.sha1(self.email).hexdigest()

class Position(models.Model):
    u"""A position within the CHARM organisation."""

    name_translations = models.ManyToManyField(StringTranslation)
    description_translations = models.ManyToManyField(TextTranslation)

    @property
    def name(self):
        u"""Either get the language we want, or get the default language. 
        Will probably throw terrible exceptions if neither is found. 
        That's a feature. The translations are regarded as broken if 
        neither a translation nor a default exists.
        
        This one breaks DRY, the original one is in BaseInfo."""
        lang = get_language().lower()
        ts   = self.name_translations.filter(Q(language__code__icontains=lang) | Q(default=True)).select_related(depth=2)
        if len(ts) > 1:
            for t in ts:
                if lang in t.language.code.lower():
                    return t.string
        else:
            if ts[0].default:
                return ts[0].string

        assert False, u'Got neither a translation nor a default language for %s, id: %s' % (self, self.pk)

    @property
    def description(self):
        u"""Either get the language we want, or get the default language. 
        Will probably throw terrible exceptions if neither is found. 
        That's a feature. The translations are regarded as broken if 
        neither a translation nor a default exists.
        
        This one breaks DRY, the original one is in BaseInfo."""
        lang = get_language().lower()
        ts   = self.description_translations.filter(Q(language__code__icontains=lang) | Q(default=True)).select_related(depth=2)
        if len(ts) > 1:
            for t in ts:
                if lang in t.language.code.lower():
                    return t.string
        else:
            if ts[0].default:
                return ts[0].string

        assert False, u'Got neither a translation nor a default language for %s, id: %s' % (self, self.pk)

    def __unicode__(self):
        return self.name

class Application(models.Model):
    person = models.ForeignKey(Person)
    state = FSMField(u'State', default=u'applied', protected=True, editable=False)

    suitability_motivation = models.CharField(ugettext_lazy(u'Are you suitable?'), help_text=ugettext_lazy(u'Motivate why you would do a good job at this post.'), max_length=255)
    preferred_position1 = models.ForeignKey(Position, verbose_name=ugettext_lazy(u'Your first preferred position'), related_name=u'application_set1')
    preferred_position2 = models.ForeignKey(Position, verbose_name=ugettext_lazy(u'Your second preferred position'), related_name=u'application_set2', blank=True, null=True) 
    preferred_position3 = models.ForeignKey(Position, verbose_name=ugettext_lazy(u'Your third preferred position'), related_name=u'application_set3', blank=True, null=True)
    approved_position = models.ForeignKey(Position, verbose_name=ugettext_lazy(u'Approved position'), related_name=u'approved_application_set', blank=True, null=True)
    
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = ugettext_lazy(u'application')
        verbose_name_plural = ugettext_lazy(u'applications')

    @property
    def translated_state(self):
        # TODO: Put the translations dictionary somewhere else, where
        # we only need to translate it a few times, like a constructor
        # or something.
        translations = {
                u'applied' : _(u'applied'),
                u'approved' : _(u'approved'),
                u'approved_not_confirmed' : _(u'approved_not_confirmed'),
                u'not_approved' : _(u'not_approved'),
                u'reserve' : _(u'reserve'),
                u'dropped_out' : _(u'dropped_out'),
            }

        return translations[self.state]

    @property
    def confirmation_hash(self):
        return hashlib.sha1(unicode(self.person) + unicode(self.created)).hexdigest()

    def __unicode__(self):
        return u'%s, %s' % (self.person, self.translated_state)

    @transition(source=u'applied', target=u'approved_not_confirmed', save=True)
    def approve(self, position):
        self.approved_position = position
        
        # Prepare an e-mail
        current_site  = Site.objects.get_current()
        mail_template = loader.get_template('recruitment/apply_confirmation_mail.txt')

apps/recruitment/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.forms.widgets import CheckboxSelectMultiple 
from django.utils.translation import ugettext as _
from django.utils.translation import ugettext_lazy
from recruitment.models import Application, ApplicationComment, Person
import string

class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        exclude = ('person', 'state', 'approved_position')

class ApplicationCommentForm(forms.ModelForm):
    class Meta:
        model = ApplicationComment
        exclude = ('person', 'application')

class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        exclude = ('user', 'email_confirmed')

        widgets = {
                'driver_license' : CheckboxSelectMultiple(),
                'forklift_license' : CheckboxSelectMultiple()
                }

    def clean_ssn(self):
        ssn = ''.join(d for d in self.cleaned_data['ssn'] if d in string.digits)
        if not len(ssn) in (10, 12):
            raise forms.ValidationError(_(u'Social security number must have a length of 10 or 12 digits.'))

        return ssn

apps/recruitment/templates/recruitment/backoffice.html
{% extends "base.html" %}
{% load i18n %}
{% block design %}

<h2>{% trans "Backoffice functionality" %}</h2>
<ul>
    <li><a href="{% url list_applications %}">{% trans "List applications" %}</a></li>
</ul>

{% endblock design %}

apps/recruitment/templates/recruitment/list_applications.html
{% extends "base.html" %}
{% load i18n %}
{% block design %}

<table border="1">
    <tr>
        <th>{% trans "State" %}</th>
        <th>{% trans "Name" %}</th>
        <th>{% trans "Phone number" %}</th>
    </tr>
    {% for application in applications %}
    <tr>
        <td class="{{application.state}}">{{application.state|capfirst}}</td>
        <td><a href="{% url show_application application.pk %}">{{application.person.fname}} {{application.person.lname}}</a></td>
        <td>{{application.person.phone}}</td>
    </tr>
    {% endfor %}
</table>


{% endblock design %}

apps/recruitment/templates/recruitment/mypage.html
{% extends "base.html" %}
{% load i18n %}
{% block design %}

<ul>
    <li><a href="{% url edit_my_profile %}">{% trans "Edit my profile" %}</a></li>
    <li><a href="{% url password_change %}">{% trans "Change password" %}</a></li>
    <li></li>
    <li><a href="{% url apply_for_position %}">{% trans "Apply for position" %}</a></li>
</ul>

{% if messages %}
<h2>{% trans "Messages" %}</h2>
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

{% if not person.email_confirmed %}
<p>{% trans "Please confirm that your e-mail address is valid by clicking on the link in the confirmation mail." %}</p>
{% endif %}

{% if person.application_set.all %}
<h2>{% trans "Applications" %}</h2>

<table>
    <tr>
        <th>{% trans "Positions" %}</th>
        <th>{% trans "State" %}</th>
    </tr>
{% for application in person.application_set.all %}
    <tr class="{{application.state}}">
        <td>{{ application.preferred_position1 }}{% if application.preferred_position2 %}, {{ application.preferred_position2 }}{% endif %}{% if application.preferred_position3 %}, {{ application.preferred_position3 }}{% endif %}</td>
        <td>{{ application.translated_state|capfirst }}{% if application.approved_position %}: {{application.approved_position}}{% endif %}</td>
    </tr>
{% endfor %}
</table>
{% endif %}

<h2>{% trans "My profile" %}</h2>

<table>
    <tr>
        <th>{% trans "First name" %}</th>
        <td>{{person.fname}}</td>
    </tr>
    <tr>
        <th>{% trans "Last name" %}</th>
        <td>{{person.lname}}</td>
    </tr>
    <tr>
        <th>{% trans "Social security number" %}</th>
        <td>{{person.ssn}}</td>
    </tr>
    <tr>
        <th>{% trans "Phone number" %}</th>
        <td>{{person.phone}}</td>
    </tr>
    <tr>
        <th>{% trans "E-mail" %}</th>
        <td>{{person.email}}</td>
    </tr>
    <tr>
        <th>{% trans "Area of study" %}</th>
        <td>{{person.study_area}}</td>
    </tr>
    <tr>
        <th>{% trans "Starting year" %}</th>
        <td>{{person.starting_year}}</td>
    </tr>
    <tr>
        <th>{% trans "driver license" %}</th>
        <td>{{person.driver_license.all|join:", "}}</td>
    </tr>
    <tr>
        <th>{% trans "forklift license" %}</th>
        <td>{{person.forklift_license.all|join:", "}}</td>
    </tr>
    <tr>
        <th>{% trans "Allergies and food preferences" %}</th>
        <td>{% if person.allergies %}{{person.allergies|linebreaks}}{% else %}{% trans "None" %}{% endif %}</td>
    </tr>
    <tr>
        <th>{% trans "shirt size" %}</th>
        <td>{{person.shirt_size}}</td>
    </tr>

    <tr>
        <td colspan="2">&nbsp;</td>
    </tr>

    <tr>
        <th>{% trans "Username" %}</th>
        <td>{{person.user.username}}</td>
    </tr>
    <tr>
        <th>{% trans "Password" %}</th>
        <td><a href="{% url password_change %}">{% trans "Change password" %}</a></td>
    </tr>
</table>

{% endblock design %}

apps/recruitment/templates/recruitment/register.html
{% extends "base.html" %}
{% load i18n %}
{% block design %}
<form method="post" action="">
    {% csrf_token %}
    <table>
        {{form}}
        <tr>
            <td colspan="2">&nbsp;</td>
        </tr>
        <tr>
            <th>&nbsp;</th>
            <td><input type="submit" value="{{button_text}}" id="submit_button"></td>
        </tr>
    </table>
</form>
{% endblock design %}

apps/recruitment/templates/recruitment/show_application.html
{% extends "base.html" %}
{% load i18n %}
{% block design %}

<p><a href="{% url list_applications %}">{% trans "Back" %}</a></p>

<form action="" method="post">
    {% csrf_token %}
    <table>
        <tr>
            <th>{% trans "State" %}</th>
            <td class="{{application.state}}">{{application.translated_state|capfirst}}{% if application.approved_position %}: {{application.approved_position}}{% endif %}</td>
        </tr>
        <tr>
            <th>{% trans "Name" %}</th>
            <td>{{application.person.fname}} {{application.person.lname}}</td>
        </tr>
        <tr>
            <th>{% trans "Phone number" %}</th>
            <td>{{application.person.phone}}</td>
        </tr>
        <tr>
            <th>{% trans "Preferred position 1" %}</th>
            <td>{% if not application.approved_position %}<input type="submit" name="pp1" value="{% trans "Approve" %}"> {% endif %}{{application.preferred_position1}}</td>
        </tr>
        <tr>
            <th>{% trans "Preferred position 2" %}</th>
            <td>{% if not application.approved_position and application.preferred_position2 %}<input type="submit" name="pp2" value="{% trans "Approve" %}"> {% endif %}{{application.preferred_position2|default:""}}</td>
        </tr>
        <tr>
            <th>{% trans "Preferred position 3" %}</th>
            <td>{% if not application.approved_position and application.preferred_position3 %}<input type="submit" name="pp3" value="{% trans "Approve" %}"> {% endif %}{{application.preferred_position3|default:""}}</td>
        </tr>
        <tr>
            <th>{% trans "Suitability motivation" %}</th>
            <td>{{application.suitability_motivation}}</td>
        </tr>
        <tr>
            <td>&nbsp;</td><td>&nbsp;</td>
        </tr>
        <tr>
            <th>{% trans "Social security number" %}</th>
            <td>{{application.person.ssn}}</td>
        </tr>
        <tr>
            <th>{% trans "E-mail" %}</th>
            <td><a href="mailto:{{application.person.email}}">{{application.person.email}}</a></td>
        </tr>
        <tr>
            <th>{% trans "Area of study" %}</th>
            <td>{{application.person.study_area}}</td>
        </tr>
        <tr>
            <th>{% trans "Starting year" %}</th>
            <td>{{application.person.starting_year}}</td>
        </tr>
        <tr>
            <th>{% trans "Driver license" %}</th>
            <td>{{application.person.driver_license.all|join:", "}}</td>
        </tr>
        <tr>
            <th>{% trans "Forklift license" %}</th>
            <td>{{application.person.forklift_license.all|join:", "}}</td>
        </tr>
        <tr>
            <th>{% trans "Allergies and food preferences" %}</th>
            <td>{% if application.person.allergies %}{{application.person.allergies|linebreaks}}{% else %}{% trans "None" %}{% endif %}</td>
        </tr>
        <tr>
            <th>{% trans "Shirt size" %}</th>
            <td>{{application.person.shirt_size}}</td>
        </tr>
    </table>
</form>

<hr>

{% for comment in application.applicationcomment_set.all %}
    <p>{{comment.person}} {{comment.created}}
    <p>{{comment.text|linebreaks}}</p>
{% endfor %}

<hr />

<form method="post" action="{% url add_application_comment application.pk %}">
    {% csrf_token %}
    <table>
        {{acform}}
        <tr>
            <th>&nbsp;</th>
            <td><input type="submit" value="{{button_text}}" id="submit_button"></td>
        </tr>
    </table>
</form>



{% endblock design %}